### ISSUE TITLE
Not working with Immich v1.109.2 - KeyError: 'diskAvailableRaw'

### ISSUE THREAD

**Issue by daedric7** [friendlyFriend4000/prometheus-immich-exporter#15]
Crashes on start as soon as it can reach Immich. Logs (trimmed for brevity):

```
prometheus-immich-exporter-1  | {"asctime": "2024-07-22 20:29:20", "levelname": "ERROR", "message": "CONNECTION ERROR. Cannot reach immich at immich-server:3001. Is immich up and running?", "taskName": null}
immich_server                 | [Nest] 16  - 07/22/2024, 8:29:21 PM     LOG [Api:EventRepository] Initialized websocket server
immich_server                 | [Nest] 16  - 07/22/2024, 8:29:21 PM     LOG [Api:SystemConfigService] LogLevel=log (set via system config)
immich_server                 | [Nest] 16  - 07/22/2024, 8:29:21 PM     LOG [Api:ServerService] Feature Flags: {
...
immich_server                 | [Nest] 16  - 07/22/2024, 8:29:21 PM     LOG [Api:NestApplication] Nest application successfully started
immich_server                 | [Nest] 16  - 07/22/2024, 8:29:21 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.109.2] [PRODUCTION]
prometheus-immich-exporter-1  | {"asctime": "2024-07-22 20:29:21", "levelname": "INFO", "message": "Found immich up and running at immich-server:3001.", "taskName": null}
prometheus-immich-exporter-1  | {"asctime": "2024-07-22 20:29:21", "levelname": "INFO", "message": "Attempting to connect to immich", "taskName": null}
prometheus-immich-exporter-1  | {"asctime": "2024-07-22 20:29:22", "levelname": "INFO", "message": "Exporter 1.2.1", "taskName": null}
prometheus-immich-exporter-1  | {"asctime": "2024-07-22 20:29:22", "levelname": "INFO", "message": "Success.", "taskName": null}
prometheus-immich-exporter-1  | {"asctime": "2024-07-22 20:29:22", "levelname": "INFO", "message": "Requested the metrics", "taskName": null}
prometheus-immich-exporter-1  | Traceback (most recent call last):
prometheus-immich-exporter-1  |   File "/usr/bin/immich_exporter", line 8, in <module>
prometheus-immich-exporter-1  |     sys.exit(main())
prometheus-immich-exporter-1  |              ^^^^^^
prometheus-immich-exporter-1  |   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 388, in main
prometheus-immich-exporter-1  |     REGISTRY.register(ImmichMetricsCollector(config))
prometheus-immich-exporter-1  |   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 40, in register
prometheus-immich-exporter-1  |     names = self._get_names(collector)
prometheus-immich-exporter-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
prometheus-immich-exporter-1  |   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 80, in _get_names
prometheus-immich-exporter-1  |     for metric in desc_func():
prometheus-immich-exporter-1  |   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 38, in collect
prometheus-immich-exporter-1  |     metrics = self.get_immich_metrics()
prometheus-immich-exporter-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^
prometheus-immich-exporter-1  |   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 58, in get_immich_metrics
prometheus-immich-exporter-1  |     metrics.extend(self.get_immich_storage())
prometheus-immich-exporter-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
prometheus-immich-exporter-1  |   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 145, in get_immich_storage
prometheus-immich-exporter-1  |     "value": (response_storage["diskAvailableRaw"]),
prometheus-immich-exporter-1  |               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
prometheus-immich-exporter-1  | KeyError: 'diskAvailableRaw'
prometheus-immich-exporter-1 exited with code 1
```

**Comment by friendlyFriend4000** [comment]
I am going to look at it over the weekend.

**Comment by friendlyFriend4000** [comment]
it works on my machine - can you double check your system?

**Comment by JakobEdvardsson** [comment]
I'm experiencing a similar issue on Immich v1.135.3. Here are my logs:

```
jul 16 20:45:39 think systemd[1]: Starting podman-immich_exporter.service...
jul 16 20:45:39 think podman[423327]: 2025-07-16 20:45:39.310002074 +0200 CEST m=+0.035545240 container create c2e6104084f8209db5c0aec02b2264811a3d9a9013bfdb90bab3b3cb63741a71 (image=docker.io/friendlyfriend/prometheus-immich-exporter:latest, name=immich_exporter, PODMAN_SYSTEMD_UNIT=podman-immich_exporter.service)
jul 16 20:45:39 think podman[423327]: 2025-07-16 20:45:39.286875849 +0200 CEST m=+0.012418992 image pull c6ce8600b1ad164f4f74570e431cda4dd687e6400712def0283d5d99f8d6a570 friendlyfriend/prometheus-immich-exporter
jul 16 20:45:39 think podman[423327]: 2025-07-16 20:45:39.499833731 +0200 CEST m=+0.225376932 container init c2e6104084f8209db5c0aec02b2264811a3d9a9013bfdb90bab3b3cb63741a71 (image=docker.io/friendlyfriend/prometheus-immich-exporter:latest, name=immich_exporter, PODMAN_SYSTEMD_UNIT=podman-immich_exporter.service)
jul 16 20:45:39 think podman[423327]: 2025-07-16 20:45:39.502802962 +0200 CEST m=+0.228346157 container start c2e6104084f8209db5c0aec02b2264811a3d9a9013bfdb90bab3b3cb63741a71 (image=docker.io/friendlyfriend/prometheus-immich-exporter:latest, name=immich_exporter, PODMAN_SYSTEMD_UNIT=podman-immich_exporter.service)
jul 16 20:45:39 think systemd[1]: Started podman-immich_exporter.service.
jul 16 20:45:39 think podman-immich_exporter-start[423327]: c2e6104084f8209db5c0aec02b2264811a3d9a9013bfdb90bab3b3cb63741a71
jul 16 20:45:39 think immich_exporter[423430]: {"asctime": "2025-07-16 18:45:39", "levelname": "INFO", "message": "Exporter is starting up", "taskName": null}
jul 16 20:45:39 think immich_exporter[423430]: {"asctime": "2025-07-16 18:45:39", "levelname": "INFO", "message": "Found immich up and running at 10.0.0.34:2283.", "taskName": null}
jul 16 20:45:39 think immich_exporter[423430]: {"asctime": "2025-07-16 18:45:39", "levelname": "INFO", "message": "Attempting to connect to immich", "taskName": null}
jul 16 20:45:40 think immich_exporter[423430]: {"asctime": "2025-07-16 18:45:40", "levelname": "INFO", "message": "Exporter 1.2.4", "taskName": null}
jul 16 20:45:40 think immich_exporter[423430]: {"asctime": "2025-07-16 18:45:40", "levelname": "INFO", "message": "Success.", "taskName": null}
jul 16 20:45:40 think immich_exporter[423430]: {"asctime": "2025-07-16 18:45:40", "levelname": "INFO", "message": "Requested the metrics", "taskName": null}
jul 16 20:45:40 think immich_exporter[423430]: Traceback (most recent call last):
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/bin/immich_exporter", line 8, in <module>
jul 16 20:45:40 think immich_exporter[423430]:     sys.exit(main())
jul 16 20:45:40 think immich_exporter[423430]:              ^^^^^^
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 392, in main
jul 16 20:45:40 think immich_exporter[423430]:     REGISTRY.register(ImmichMetricsCollector(config))
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 40, in register
jul 16 20:45:40 think immich_exporter[423430]:     names = self._get_names(collector)
jul 16 20:45:40 think immich_exporter[423430]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 80, in _get_names
jul 16 20:45:40 think immich_exporter[423430]:     for metric in desc_func():
jul 16 20:45:40 think immich_exporter[423430]:                   ^^^^^^^^^^^
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 39, in collect
jul 16 20:45:40 think immich_exporter[423430]:     metrics = self.get_immich_metrics()
jul 16 20:45:40 think immich_exporter[423430]:               ^^^^^^^^^^^^^^^^^^^^^^^^^
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 59, in get_immich_metrics
jul 16 20:45:40 think immich_exporter[423430]:     metrics.extend(self.get_immich_storage())
jul 16 20:45:40 think immich_exporter[423430]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^
jul 16 20:45:40 think immich_exporter[423430]:   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 147, in get_immich_storage
jul 16 20:45:40 think immich_exporter[423430]:     "value": (response_storage["diskAvailableRaw"]),
jul 16 20:45:40 think immich_exporter[423430]:               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
jul 16 20:45:40 think immich_exporter[423430]: KeyError: 'diskAvailableRaw'
jul 16 20:45:40 think podman[423446]: 2025-07-16 20:45:40.68521206 +0200 CEST m=+0.012034538 container died c2e6104084f8209db5c0aec02b2264811a3d9a9013bfdb90bab3b3cb63741a71 (image=docker.io/friendlyfriend/prometheus-immich-exporter:latest, name=immich_exporter, PODMAN_SYSTEMD_UNIT=podman-immich_exporter.service)
jul 16 20:45:41 think podman[423446]: 2025-07-16 20:45:41.075601501 +0200 CEST m=+0.402424009 container remove c2e6104084f8209db5c0aec02b2264811a3d9a9013bfdb90bab3b3cb63741a71 (image=docker.io/friendlyfriend/prometheus-immich-exporter:latest, name=immich_exporter, PODMAN_SYSTEMD_UNIT=podman-immich_exporter.service)
jul 16 20:45:41 think systemd[1]: podman-immich_exporter.service: Main process exited, code=exited, status=1/FAILURE
jul 16 20:45:41 think systemd[1]: podman-immich_exporter.service: Failed with result 'exit-code'.
jul 16 20:45:41 think systemd[1]: podman-immich_exporter.service: Consumed 399ms CPU time, 14.9M memory peak, 296K written to disk, 224B outgoing IP traffic.
jul 16 20:45:41 think systemd[1]: podman-immich_exporter.service: Scheduled restart job, restart counter is at 169.
``` 

I was able to get the storage using curl so not sure what the issue is:
```sh
curl -X GET http://10.0.0.34:2283/api/server/storage \                                                                                                                
                      -H "Accept: application/json" \                                                                                                                                 
                      -H "x-api-key: <token>"
```

Update1: getting 401 so something is wrong with auth

solved: nixos was the problem, the api key didn't work correctly (api key must be from the admin user, if I'm not misstaken).

**Comment by tvann2182** [comment]
I am now also experiencing this issue with the latest version of immich. v 1.136.0, I seen the above comment so I wiped out my api key and created a new one to alleviate that as a potential issue. Please help if you can. running on Unraid. API Key was created under admin account.


```

 "2025-07-31 16:09:37", "levelname": "INFO", "message": "Exporter is starting up", "taskName": null}
{"asctime": "2025-07-31 16:09:37", "levelname": "INFO", "message": "Found immich up and running at 10.0.5.10:8080.", "taskName": null}
{"asctime": "2025-07-31 16:09:37", "levelname": "INFO", "message": "Attempting to connect to immich", "taskName": null}
{"asctime": "2025-07-31 16:09:38", "levelname": "INFO", "message": "Exporter 1.2.4", "taskName": null}
{"asctime": "2025-07-31 16:09:38", "levelname": "INFO", "message": "Success.", "taskName": null}
{"asctime": "2025-07-31 16:09:38", "levelname": "INFO", "message": "Requested the metrics", "taskName": null}
Traceback (most recent call last):
  File "/usr/bin/immich_exporter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 392, in main
    REGISTRY.register(ImmichMetricsCollector(config))
  File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
                  ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 39, in collect
    metrics = self.get_immich_metrics()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 59, in get_immich_metrics
    metrics.extend(self.get_immich_storage())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 147, in get_immich_storage
    "value": (response_storage["diskAvailableRaw"]),
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'diskAvailableRaw'

```

**Comment by Allram** [comment]
> I am now also experiencing this issue with the latest version of immich. v 1.136.0, I seen the above comment so I wiped out my api key and created a new one to alleviate that as a potential issue. Please help if you can. running on Unraid. API Key was created under admin account.
> 
> ```
> 
>  "2025-07-31 16:09:37", "levelname": "INFO", "message": "Exporter is starting up", "taskName": null}
> {"asctime": "2025-07-31 16:09:37", "levelname": "INFO", "message": "Found immich up and running at 10.0.5.10:8080.", "taskName": null}
> {"asctime": "2025-07-31 16:09:37", "levelname": "INFO", "message": "Attempting to connect to immich", "taskName": null}
> {"asctime": "2025-07-31 16:09:38", "levelname": "INFO", "message": "Exporter 1.2.4", "taskName": null}
> {"asctime": "2025-07-31 16:09:38", "levelname": "INFO", "message": "Success.", "taskName": null}
> {"asctime": "2025-07-31 16:09:38", "levelname": "INFO", "message": "Requested the metrics", "taskName": null}
> Traceback (most recent call last):
>   File "/usr/bin/immich_exporter", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 392, in main
>     REGISTRY.register(ImmichMetricsCollector(config))
>   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 40, in register
>     names = self._get_names(collector)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 80, in _get_names
>     for metric in desc_func():
>                   ^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 39, in collect
>     metrics = self.get_immich_metrics()
>               ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 59, in get_immich_metrics
>     metrics.extend(self.get_immich_storage())
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 147, in get_immich_storage
>     "value": (response_storage["diskAvailableRaw"]),
>               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
> KeyError: 'diskAvailableRaw'
> ```

What rights did you give your new API key?
