### ISSUE TITLE
Breaking Change with v1.117.0

### ISSUE THREAD

**Issue by dwhitnall** [friendlyFriend4000/prometheus-immich-exporter#17]
With the latest version of Immich the API has changed location from "/api/server-info/statistics" to "/api/server/statistics"
As a result the container continues restarting as it can't get to the endpoint.

Exporter is starting up | asctime=2024-10-13 08:27:09 levelname=INFO taskName=null

Found immich up and running at immich-server:2283. | asctime=2024-10-13 08:27:09 levelname=INFO taskName=null

Attempting to connect to immich | asctime=2024-10-13 08:27:09 levelname=INFO taskName=null

Exporter 1.2.1 | asctime=2024-10-13 08:27:10 levelname=INFO taskName=null

Success. | asctime=2024-10-13 08:27:10 levelname=INFO taskName=null

Requested the metrics | asctime=2024-10-13 08:27:10 levelname=INFO taskName=null

Traceback (most recent call last):

  File "/usr/bin/immich_exporter", line 8, in <module>

    sys.exit(main())

             ^^^^^^

  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 388, in main

    REGISTRY.register(ImmichMetricsCollector(config))

  File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 40, in register

    names = self._get_names(collector)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/prometheus_client/registry.py", line 80, in _get_names

    for metric in desc_func():

  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 38, in collect

    metrics = self.get_immich_metrics()

              ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 57, in get_immich_metrics

    metrics.extend(self.get_immich_server_version_number())

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/immich_exporter/exporter.py", line 186, in get_immich_server_version_number

    str(response["major"]) + "." + str(response["minor"]) + "." + str(response["patch"])

        ~~~~~~~~^^^^^^^^^

KeyError: 'major'

**Comment by MaxenceG2M** [comment]
Should be fixed with PR #19

**Comment by friendlyFriend4000** [comment]
should be working with 1.118.2 now. thanks
